version: '3.7'

services:
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-enterprise/auth-server
    container_name: auth-server
#    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_LOCATION=file:/resources/application.yml
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - $PWD/src/main/resources:/resources
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2
    container_name: postgres
    restart: always
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  auth-db-data:
    driver: local