version: '3.7'

services:
  postgres:
    image: postgres:11.2
    container_name: auth-db
    restart: always
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  auth-db-data:
    driver: local